# Generated by Django 3.1.2 on 2020-12-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=34)),
                ('email', models.CharField(max_length=34)),
                ('phno', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
