# Generated by Django 3.1.2 on 2020-12-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_recipe', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='phno',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
