# Generated by Django 3.1.2 on 2020-12-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_recipe', '0003_auto_20201209_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='phno',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
