# Generated by Django 3.1.2 on 2020-12-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_recipe', '0004_auto_20201209_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='phno',
            field=models.IntegerField(blank=True),
        ),
    ]
